### ISSUE TITLE
A2.8-d

### ISSUE THREAD

**Issue by JuanluRM** [gii-is-psg2/psg2-2223-g5-52#15]
Add delete support to all main domain objects (owners, pets, veterinarians…).

**Comment by darkgigi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/G5-52-6408606591a5d9001540683f/issues/gii-is-psg2/psg2-2223-g5-52/15?planning-poker) with Zenhub @guigalde @JesusSolisOrtega @josruiper4 @JuanluRM @PedroRuizAguilar
