### ISSUE TITLE
Acta de retrospectiva scrum

### ISSUE THREAD

**Issue by guigalde** [gii-is-psg2/psg2-2223-g5-52#45]

**Comment by darkgigi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/G5-52-6408606591a5d9001540683f/issues/gii-is-psg2/psg2-2223-g5-52/45?planning-poker) with Zenhub @guigalde @JuanluRM @PedroRuizAguilar @josruiper4 @JesusSolisOrtega
