### ISSUE TITLE
A4.3.b Support Team Page

### ISSUE THREAD

**Issue by JuanluRM** [gii-is-psg2/psg2-2223-g5-52#87]
Support page: Provide the contact details (web page, emails and phone numbers) of the support team of the Petclinic application. Do not use real data!

**Comment by darkgigi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG3-2223-G5-52-6408606591a5d9001540683f/issues/gii-is-psg2/psg2-2223-g5-52/87?planning-poker) with Zenhub @guigalde @JesusSolisOrtega @josruiper4 @JuanluRM @PedroRuizAguilar

**Comment by JesusSolisOrtega** [comment]
Bien realizado. Icono bien elegido y no sobrecarga el menú superior.

No obstante ha sido difícil encontrar el icono al principio. Se sugiere que se mejore de alguna forma la visibilidad del mismo.
