### ISSUE TITLE
A4.3.d Contract-aware GUI

### ISSUE THREAD

**Issue by JuanluRM** [gii-is-psg2/psg2-2223-g5-52#90]
Contract-aware GUI (three or more requests): Adjust the application GUI to the pricing plan associated with the logged-in user. This feature will be rolled out incrementally, meaning that for the first request the updated application will only support the Basic plan. The Advanced plan will also be supported in a subsequent update, and the final update will support the Pro plan.

**Comment by darkgigi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG3-2223-G5-52-6408606591a5d9001540683f/issues/gii-is-psg2/psg2-2223-g5-52/90?planning-poker) with Zenhub @guigalde @JesusSolisOrtega @josruiper4 @JuanluRM @PedroRuizAguilar
