### ISSUE TITLE
A4.2c Pricing

### ISSUE THREAD

**Issue by guigalde** [gii-is-psg2/psg2-2223-g5-52#94]
There must exist at least three plans (Basic, Advanced and Pro), whose conditions each group can establish at their convenience, provided that the following constraints are fulfilled:
The Basic plan does not offer SLA
The Advanced plan is the first to allow clinic owners to manage multiple pet clinics.
The Pro plan is the only one offering support for user requests and RFCs.
The maximum number of vets, monthly visits, and pet types allowed must differ for each plan.
Service availability must be different for each plan. This information should be represented using a matrix, as is customary nowadays.

**Comment by darkgigi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG3-2223-G5-52-6408606591a5d9001540683f/issues/gii-is-psg2/psg2-2223-g5-52/94?planning-poker) with Zenhub @guigalde @JesusSolisOrtega @josruiper4 @JuanluRM @PedroRuizAguilar

**Comment by PedroRuizAguilar** [comment]
Respecto a la parte de la disponibilidad del servicio veo beneficioso ofrecer al usuario porcentajes así como hemos visto de ejemplos en clase, también el plan pro debe tener algo de soporte ya que también esta pagando, podrías hacer una nueva fila como en algunos ejemplos de clase en la que especifica que su soporte seria con un chat y el del plan premium puede ser con el chat o llamando y que alguien le atienda.
El número de mascotas es algo pequeño, por lo demás buena matriz
